package com.jongheon.myreadle.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF0F62FE)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDDE7FF)
val LightOnPrimaryContainer = Color(0xFF001A41)
val LightSecondary = Color(0xFF4A5868)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE6EAF2)
val LightOnSecondaryContainer = Color(0xFF1A2330)
val LightBackground = Color(0xFFFAFAFB)
val LightOnBackground = Color(0xFF1A1B1F)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF1A1B1F)
val LightSurfaceVariant = Color(0xFFEEF1F6)
val LightOnSurfaceVariant = Color(0xFF44474F)
val LightOutline = Color(0xFFCBD5E1)
val LightTertiary = Color(0xFF38BDF8)
val LightOnTertiary = Color(0xFF002633)

val DarkPrimary = Color(0xFFB1C6FF)
val DarkOnPrimary = Color(0xFF002E69)
val DarkPrimaryContainer = Color(0xFF1F438F)
val DarkOnPrimaryContainer = Color(0xFFDDE7FF)
val DarkSecondary = Color(0xFFB8C5D6)
val DarkOnSecondary = Color(0xFF223044)
val DarkSecondaryContainer = Color(0xFF38465A)
val DarkOnSecondaryContainer = Color(0xFFD3E0F2)
val DarkBackground = Color(0xFF0F1115)
val DarkOnBackground = Color(0xFFE3E2E6)
val DarkSurface = Color(0xFF15181E)
val DarkOnSurface = Color(0xFFE3E2E6)
val DarkSurfaceVariant = Color(0xFF1F232B)
val DarkOnSurfaceVariant = Color(0xFFC4C6CF)
val DarkOutline = Color(0xFF3A4150)
val DarkTertiary = Color(0xFF38BDF8)
val DarkOnTertiary = Color(0xFF002633)

val VocabUnderlineLight = Color(0xFF1D4ED8)
val VocabUnderlineDark = Color(0xFF93C5FD)
